# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: arrizalamin.portfolio::lang.controller.form.items.title

# Model Form Field configuration
form: $/arrizalamin/portfolio/models/item/fields.yaml

# Model Class name
modelClass: ArrizalAmin\Portfolio\Models\Item

# Default redirect location
defaultRedirect: arrizalamin/portfolio/items

# Create page
create:
    title: arrizalamin.portfolio::lang.controller.form.items.create
    redirect: arrizalamin/portfolio/items/update/:id
    redirectClose: arrizalamin/portfolio/items

# Update page
update:
    title: arrizalamin.portfolio::lang.controller.form.items.update
    redirect: arrizalamin/portfolio/items
    redirectClose: arrizalamin/portfolio/items