# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/arrizalamin/portfolio/models/category/fields.yaml

# Model Class name
modelClass: ArrizalAmin\Portfolio\Models\Category

# Default redirect location
defaultRedirect: arrizalamin/portfolio/categories

# Create page
create:
    title: Create Category
    redirect: arrizalamin/portfolio/categories/update/:id
    redirectClose: arrizalamin/portfolio/categories

# Update page
update:
    title: Edit Category
    redirect: arrizalamin/portfolio/categories
    redirectClose: arrizalamin/portfolio/categories

# Preview page
preview:
    title: Preview Category